<?php 

$ps = [
    'type'=>[
       "Residential",
    "Commercial",
    "Industrial",
    "Retail",
    "Mixed-Use",
    "Agricultural",
    "Recreational",
    "Institutional",
    "Land",
    "Luxury Apartments",
    "Bungalows",
    "Duplexes",
    "Terrace Houses",
    "Detached Houses",
    "Semi-Detached Houses",
    "Flats/Apartments",
    "Mansions",
    "Townhouses",
    "Villas",
    "Warehouses",
    "Office Spaces",
    "Shops",
    "Shopping Malls",
    "Hotels",
    "Resorts",
    "Farms",
    "Factories",
    "Schools",
    "Hospitals",
    "Event Centers",
    "Studio Apartments",
    "Penthouse Apartments",
    "Serviced Apartments",
    "Shortlet Apartments",
    "Cottages",
    "Hostels",
    "Blocks of Flats",
    "Workshops",
    "Showrooms",
    "Conference Centers",
    "Churches",
    "Mosques",
    "Markets",
    "Golf Courses",
    "Parks"
    ],
    'status'=>[
        "For Sale",
    "For Rent",
    "Leased",
    "Shortlet",
    "Auction"
    ],
    'rooms'=>[
        '1', '2', '3', '4', 'Not applicable',
    ],
    'amenities'=>[
  "air conditioning",
  "lawn",
  "swimming pool",
  "barbeque",
  "microwave",
  "tv cable",
  "dryer",
  "outdoor shower",
  "washer",
  "gym",
  "refrigerator",
  "wifi",
  "laundry",
  "sauna",
  "window coverings"
]
];